import localFont from "next/font/local";
import "@/public/css/globals.css";
import { getMessages } from 'next-intl/server';
import Image from "next/image";

const geistSans = localFont({
  src: "../..//public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../..//public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = params;
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-12">
          <div className="h-12 w-12">
            <Image src="/public/images/logo.png" width={100} height={80} />
          </div>
        </header>
          {children}
      </body>
    </html>
  );
}
